import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";

import { ClerkProvider } from "@clerk/nextjs";
import { auth, currentUser } from "@clerk/nextjs/server";

const dosis = Dosis({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const user = await currentUser();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={dosis.className + " bg-[var(--light-tan)] text-[var(--dark-purple)]"}>
          <TopNav/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
